### ISSUE TITLE
Documentation issue (CMake)

### ISSUE THREAD

**Issue by l0calh05t** [AustinBrunkhorst/CPP-Reflection#1]
In README.md you state

> **Note:** this assumes you have created empty files for `${META_GENERATED_HEADER}` and `${META_GENERATED_SOURCE}` and added it to the list of sources when calling `add_executable( )`. Otherwise, CMake will complain about the files not existing initially.

The recommended approach is not to create empty files for generated files (especially as you will be tempted to put them in the source directory instead of the build directory). Instead you should set the `GENERATED` on the corresponding sources:

``` CMake
set_source_files_properties(
    ${META_GENERATED_HEADER} ${META_GENERATED_SOURCE}
    PROPERTIES
    GENERATED ON
)
```

Furthermore you use a `PRE_BUILD` `TARGET` `add_custom_command` which only works on Visual Studio. Using a non-`TARGET` `add_custom_command` might be better (and also sets the `GENERATED` property automatically).

**Comment by AustinBrunkhorst** [comment]
This is fantastic! I was unaware of the `GENERATED` source files property.

I was also unaware that `add_custom_command(TARGET ...)` only works in Visual Studio, but this makes sense.

> (and also sets the GENERATED property automatically)

Can you explain what you mean by this? Sets the `GENERATED` property for what exactly?

**Edit**

From `add_custom_command( ... )` documentation -

> ... This defines a command to generate specified OUTPUT file(s). A target created in the same directory (CMakeLists.txt file) that specifies any output of the custom command as a source file is given a rule to generate the file using the command at build time ...

Clears it up for me.

**Comment by l0calh05t** [comment]
It's not the `add_custom_command(TARGET ...)` form per se that only works on VS, but the `PRE_BUILD` mode of that command. In any case, I believe the `add_custom_command(OUTPUT ...)` form is a better fit.

**Comment by AustinBrunkhorst** [comment]
Using `add_custom_command(OUTPUT ...)`, how can I ensure the command is run before a specific target is built? (_aka the `PRE_BUILD` stage of a specific target in Visual Studio_). 

I tested this method, and it works, however I don't understand the `MAIN_DEPENDENCY`, `DEPENDS`, and `IMPLICIT_DEPENDS` options.

**Comment by l0calh05t** [comment]
Just include the outputs in the target's `add_library` or `add_executable` command, and they will be generated before the target is built.

`MAIN_DEPENDENCY` is just to make the Makefile itself look nice. `DEPENDS` is a list of files that should be monitored for changes (the files are generated only if they don't exist or one of the dependencies changes), basically this should be all your (other) header and source files. `IMPLICIT_DEPENDS` would actually be the ideal solution as it would trigger the dependency determination also used for building cpp/c files (all .h files, even system headers and libraries would be pulled in). However, it only works for unix makefiles.

There are hacks to get pre-build like behavior with all generators, but that gets real ugly, real quick, see, e.g., http://stackoverflow.com/questions/3780667/use-cmake-to-get-build-time-svn-revision

**Comment by AustinBrunkhorst** [comment]
I just realized your solution is actually much more desirable than a pre-build step. Only project header files effect the generated reflection files. Therefore, it makes sense to use _only_ project header files in the `DEPENDS` option of the `add_custom_command(OUTPUT ...)`.

With a pre-build step, the reflection files will be regenerated even if only a source file is changed, which is not desired.

I'll update the readme to reflect these changes! Thanks again.
