### ISSUE TITLE
Doesn't compile with visual studio 2017

### ISSUE THREAD

**Issue by LogicalError** [AustinBrunkhorst/CPP-Reflection#12]
If I compile this with visual studio 2017 (w/ cmake) it'll give an "Cannot use Argument as an argument" error.

**Comment by AustinBrunkhorst** [comment]
I haven't tried compiling with Visual Studio 2017 yet. Can you give me more details of the compilation error?

**Comment by AustinBrunkhorst** [comment]
I've been away from this project for quite some time, but just got around to installing 2017. I am currently investigating this!
