### ISSUE TITLE
can you add some document about cmake rule?

### ISSUE THREAD

**Issue by chena1982** [AustinBrunkhorst/CPP-Reflection#14]
it's a cool library, thanks.
i use the library in my project, i write my cmake file on the basis of example's cmake file.
i generate the vs project, and generate the needed meta files, but these files is empty.
i can't debug this, i don't know where is wrong.
can you add some document about cmake rule?
for example, explain the "meta_parser_prebuild" and "meta_parser_build".
Thanks.

**Comment by chena1982** [comment]
i get the reason, the "add_custom_command" of "meta_parser_build" don't work.
the project don't have the post build event.

**Comment by AustinBrunkhorst** [comment]
Can you post the relevant portions of your `CMakeLists.txt`? It really depends on how you have integrated it with your project. I'll take a look and see if I notice any issues. 

I plan on writing better documentation all around. As of right now, this repository is mainly just a tech demo. Don't you worry though!

**Comment by chena1982** [comment]
Thanks for your reply, some part of my cmakelists.txt is below:

```
set(${LIB_NAME}_META_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
set(${LIB_NAME}_META_GENERATED_DIR "${CMAKE_CURRENT_LIST_DIR}/Generated")

set(${LIB_NAME}_META_GENERATED_HEADERS "")
set(${LIB_NAME}_META_GENERATED_SOURCES "")

set(${LIB_NAME}_REFLECTION_HEADER ${LIB_NAME}Header.h)
set(${LIB_NAME}_MODULE_HEADER ${LIB_NAME}Module.h)


set(${LIB_NAME}_HEADERS EFFGUILayoutInfo.h)


meta_parser_prebuild(
    TARGET ${LIB_NAME}
    GENERATED_DIR ${${LIB_NAME}_META_GENERATED_DIR}
    SOURCE_ROOT ${${LIB_NAME}_META_SOURCE_ROOT}
    HEADER_FILES ${${LIB_NAME}_HEADERS}
    MODULE_HEADER ${${LIB_NAME}_MODULE_HEADER}
    OUT_MODULE_SOURCE META_MODULE_SOURCE
    OUT_GENERATED_FILES META_GENERATED_FILES
    OUT_INC ${LIB_NAME}_META_GENERATED_HEADERS
    OUT_SRC ${LIB_NAME}_META_GENERATED_SOURCES
)


add_library(${LIB_NAME} SHARED ${META_GENERATED_FILES})

meta_parser_build(
    TARGET ${LIB_NAME}
    SOURCE_ROOT ${${LIB_NAME}_META_SOURCE_ROOT}
    GENERATED_DIR ${${LIB_NAME}_META_GENERATED_DIR}
    GENERATED_FILES ${META_GENERATED_FILES}
    SOURCE_FILE ${${LIB_NAME}_REFLECTION_HEADER}
    MODULE_HEADER ${${LIB_NAME}_MODULE_HEADER}
    MODULE_SOURCE_FILE ${META_MODULE_SOURCE}
    HEADER_FILES ${${LIB_NAME}_HEADERS}
    PCH_NAME ${LIB_NAME}PCH
    PARSER_EXECUTABLE "${CMAKE_SOURCE_DIR}/Bin/MetaParser.exe"
)
```
${LIB_NAME} is EFFReflection.

EFFGUILayoutInfo.h contain a enum use meta.

${LIB_NAME}Header.h content is
```
#pragma once
#include "EFFGUILayoutInfo.h"
```

${LIB_NAME}Module.h cotent is
```
#pragma once


#include <ReflectionModule.h>

DECLARE_REFLECTION_MODULE(EFFReflection);
```

EFFGUILayoutInfo.Generated.h and EFFGUILayoutInfo.Generated.cpp is empty.

Look forward to the documentation, thanks for your share.

**Comment by AustinBrunkhorst** [comment]
You mention that you generate the project solution - have you built the project? The actual parser is not run (filling the contents of the generated files with the reflection data) until the pre-build step. 

If you _have_ built, and the parser still isn't run, try `touch`ing one of the source files just for a sanity check. I suspect there is might be an issue with handling all out of date files properly, which I will address.

**Comment by chena1982** [comment]
I find the problem.
When build the testmodule project, it output:
"Building Custom Rule D:/GitHub/Cpp-Reflection/Examples/CMakeLists.txt"

When build my project, don't execute this.

The D:\EFF\Src\EFFReflection\CMakeLists.txt custom build command line is:
"D:\Program Files\cmake-3.9.0-win64-x64\bin\cmake.exe" -HD:/EFF -BD:/EFF/Build --check-stamp-file D:/EFF/Build/Src/EFFReflection/CMakeFiles/generate.stamp

It seems that D:/EFF should be D:\EFF\Src\EFFReflection, EFFReflection project is a subdirectory of EFF.
I'm not very familiar with cmake, is it because of that?


PS, i found rebuild the testmodule project will failed, is that a bug?

**Comment by chena1982** [comment]
yes, i change D:/EFF to D:\EFF\Src\EFFReflection, it execute the pre-build now.
but the generated EFFGUILayoutInfo.Generated.cpp don't contain meta info,
just contain the pch info.
```
#include "EFFReflectionPCH.h"
```

**Comment by chena1982** [comment]
yes, i change it to D:\EFF\Src\EFFReflection, it execute the pre-build step now.
but generated file is still empty except contain the pch info.

**Comment by chena1982** [comment]
add --display-diagnostics true to "add_custom_command" of the MetaParse.cmake.
i find the problem now, clang 4.0.1 not work well with vs2017 and boost 1.64.0.
