### ISSUE TITLE
The examples can not work on Mac OS!

### ISSUE THREAD

**Issue by youZhuang** [AustinBrunkhorst/CPP-Reflection#16]
I found the content of generated files is empty!
the compile error is :

Undefined symbols for architecture x86_64:
  "meta_generated::ModuleTestModule::ModuleTestModule(ursine::meta::ReflectionDatabase&)", referenced from:
      _main in Enums.o
  "meta_generated::ModuleTestModule::~ModuleTestModule()", referenced from:
      _main in Enums.o

**Comment by littleArtherSong** [comment]
same question
