### ISSUE TITLE
TypeInfo.hpp DecayedType

### ISSUE THREAD

**Issue by brunogouveia** [AustinBrunkhorst/CPP-Reflection#6]
I think this [line](https://github.com/AustinBrunkhorst/CPP-Reflection/blob/ea038f4bc3d9bc44193221597559c994c995d380/Source/Runtime/Impl/TypeInfo.hpp#L29) should be:

``` C++
typedef typename std::decay<T>::type Decayed;
```

rather than:

``` C++
typedef std::decay<T> Decayed;
```

Because you wanna check if the decayed type of `T` is a primitive/enum/class/etc.. and not check if the instantiated template `std::decay<T>` is a primitive/enum/class/etc.. (which would always generate the same results: class = true, primitive = false, enum =false).

**Comment by AustinBrunkhorst** [comment]
You're correct! Thank you for pointing that out.
