### ISSUE TITLE
No Build Project Description

### ISSUE THREAD

**Issue by molixiaoge** [AustinBrunkhorst/CPP-Reflection#7]
Can you tell me how to build the project?Thanks.

**Comment by thekitchensink** [comment]
This isn't a project that can be "built", per se: it's a library to use.

**Comment by AustinBrunkhorst** [comment]
Hi guys! I'm in the process of pushing some changes that make this build-able within the next couple of days. Stay tuned!

**Comment by AustinBrunkhorst** [comment]
It's pushed! Thanks for being patient and let me know if you have any questions.
