### ISSUE TITLE
Examples fail to link

### ISSUE THREAD

**Issue by ArnauPrat** [AustinBrunkhorst/CPP-Reflection#8]
Hi  @AustinBrunkhorst 
When compiling the Examples, everything seems to go fine (both Parser and Runtime compile) but the Serialization.cpp fails to link. This is the output I get. If I look at the files of the Generated folder, all of them but the *.includes one are empty. I think there is something wrong with the meta_parser_build command, like if it was not triggering the Parser. Any ideas?

```
[ 23%] Built target MetaParser
[ 55%] Built target MetaRuntime
[ 61%] Built target TestModule
[ 62%] Linking CXX executable Serialization
CMakeFiles/Serialization.dir/Serialization.cpp.o: En la función `main':
Serialization.cpp:(.text+0xcb): referencia a `meta_generated::ModuleTestModule::ModuleTestModule(ursine::meta::ReflectionDatabase&)' sin definir
Serialization.cpp:(.text+0xda): referencia a `meta_generated::ModuleTestModule::~ModuleTestModule()' sin definir
collect2: error: ld devolvió el estado de salida 1
make[2]: *** [CMakeFiles/Serialization.dir/build.make:193: Serialization] Error 1
make[1]: *** [CMakeFiles/Makefile2:70: CMakeFiles/Serialization.dir/all] Error 2
```

I am under linux, using GCC 6.2.0, libclang 3.8.1 and boost 1.6.1
Best,
Arnau

**Comment by AustinBrunkhorst** [comment]
Hello there!

It does look like the pre-build parser step is not being run, which would cause the linker errors. Just to confirm, is there **Parsing reflection data for target "..."** anywhere in the output?

Also, are you using the `cmake --build` command?

**Comment by ArnauPrat** [comment]
Hi again!
No *_Parsing reflection data for target "..." \* in the output_
I tried with both cmake --build . and direclty calling make, with the same outcome.
This is the output of calling cat ./\* inside the Generated folder:

```
 cat ./*
/home/aprat/projects/personal/owc/lib/reflection/Source/Runtime
/home/aprat/projects/personal/owc/lib/reflection/Source/Runtime/..
/home/aprat/projects/personal/owc/lib/reflection/Source/Runtime/../Common/Lib
```

ls ./\* shows the following:

```
Module.TestModule.Generated.cpp  TestProperties.Generated.cpp  TestTypes.Generated.cpp
Module.TestModule.Includes.txt   TestProperties.Generated.h    TestTypes.Generated.h
```

As you can see, files are empty. I'll try to investigate why the Parser is not being executed.
Thanks for your help
Arnau

**Comment by ArnauPrat** [comment]
Hi again @AustinBrunkhorst 
My five cents on my investigation. IF I comment out [this if-else statement](https://github.com/AustinBrunkhorst/CPP-Reflection/blob/master/Source/CMake/MetaParser.cmake#L132) (from 132 to 138), everything goes well. I understandy that this code basically creates the empty generated files. Then, when building with make, since it already finds these files available (though empty), it does not trigger the command to generate them. Does this make sense?
Thanks
Arnau

**Comment by AustinBrunkhorst** [comment]
@ArnauPrat This does make sense.

CMake requires files to exist in order to be included in a list of sources, so writing the files _was_ necessary before calling `add_executable` or `add_library`. I have since completely re-written the entire pipeline - among the changes was a great suggestion from @l0calh05t [here](https://github.com/AustinBrunkhorst/CPP-Reflection/issues/1) which makes use of the `GENERATED` source file property, which allows sources to not exist.

I'm pretty sure writing empty files in `meta_parser_build` is just me forgetting to remove it after the refactor. I will test removing it!

Thank you for taking the time to investigate this.

Cheers

**Comment by DongSirOh** [comment]
@AustinBrunkhorst Hi
when I build the Examples,it show me the message "error MSB6006: “cmd.exe” exited with code  -1073741819" after **Parsing reflection data for target "..."**  in the output.
So,I tried ro debug the Parser,it show me the message "**access violation executing location ...**" when call the "clang_Cursor_getStorageClass(child)" form some Cursor.
I am under Win10 x64, using Cmake3.14.4, VS2015, libclang 3.8.0 and boost 1.59.1
Best,
Aaron.

**Comment by AustinBrunkhorst** [comment]
Sorry for the inactivity here folks. I'll get back to these issues in the near months, but plan to facilitate any pull requests if that is something that anyone is interested in!

Thanks.
