### ISSUE TITLE
Get Type with string name  Problem.

### ISSUE THREAD

**Issue by molixiaoge** [AustinBrunkhorst/CPP-Reflection#9]
In Test Projects With MetaProperties.The Code Say:
`// you can also use type meta::Type::Get( "SoundEffect" ) based on a string name
Type soundEffectType =  typeof( SoundEffect );`

But,when i Replace the code with:
`Type soundEffectType = ursine::meta::Type::Get("SoundEffect");`

The soundEffectType  Result not Right! SoundEffectType.m_id is 0,and then the program crash with null pointer read!

**Comment by AustinBrunkhorst** [comment]
That was a typo! It should be `meta::Type::GetFromName( "SoundEffect" )`. Thanks for pointing that out.

**Comment by molixiaoge** [comment]
Ok, thanks for you reply!
